/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TSB_Viejo.CapaPresentacion;

import DB.DB;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

import javax.swing.table.TableRowSorter;

/**
 *
 * @author jorge
 */
public class Busqueda extends javax.swing.JFrame {

    private TableRowSorter trsfiltro;
    private DB baseDatos;

    /**
     * Creates new form Busqueda
     */
    public Busqueda() {
        
        initComponents();
        setTitle("Buscar Palabra");
        
        iniciar();
        //llenarCombo();
        //Modelo();
        //Listener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        lblPalabra = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTextField1.setEnabled(false);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        lblPalabra.setText("Palabra a Buscar:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Palabra", "Apariciones", "Documentos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jButton1.setText("Cargar");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setEnabled(false);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel1.setText("Diccionario: ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblPalabra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jComboBox1, 0, 154, Short.MAX_VALUE))
                        .addGap(90, 90, 90)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPalabra))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVolver)
                    .addComponent(btnLimpiar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
        jTextField1.addKeyListener(new KeyAdapter() {
            public void keyReleased(final KeyEvent e) {
                String cadena = (jTextField1.getText());
                jTextField1.setText(cadena);
                repaint();
                filtro();
            }
        });
        trsfiltro = new TableRowSorter(Modelo_Tabla);
        jTable1.setRowSorter(trsfiltro);
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jComboBox1.getItemCount() == 1) {
            JOptionPane.showMessageDialog(null, " Error: No hay diccionarios cargados");
        }
                Modelo();
                Obtener_Datos();
                trsfiltro = new TableRowSorter(Modelo_Tabla);
                jTable1.setRowSorter(trsfiltro);
                 btnLimpiar.setEnabled(true);
                jButton1.setEnabled(false);
                jTextField1.setEnabled(true);
                jComboBox1.setEnabled(false);

        


    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        trsfiltro = null;
        jTable1.setRowSorter(trsfiltro);
        jTable1.setModel(new DefaultTableModel());
        btnLimpiar.setEnabled(false);
        jButton1.setEnabled(true);
        
        jTextField1.setEnabled(false);
        jComboBox1.setEnabled(true);
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        PantallaGenerarDiccionario pgd = new PantallaGenerarDiccionario();
        pgd.setVisible(true);
        //mato el formualrio
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    
    
    private void iniciar(){
        SwingWorker worker = new SwingWorker<ImageIcon[], Void>() {
            @Override
            public ImageIcon[] doInBackground() {
                baseDatos = new DB();
                llenarCombo();
                Listener();
                
                return null;
            }
                
            };
              worker.execute();
            }
    public void Listener(){
        jComboBox1.addItemListener( new ItemListener(){

            @Override
            public void itemStateChanged(ItemEvent e) {
                if ( e.getStateChange() == ItemEvent.SELECTED ) 
                {
                    if(jComboBox1.getSelectedIndex()==0){
                        JOptionPane.showMessageDialog(null, "Seleccione un diccionario valido");
                        jButton1.setEnabled(false);
                    }else{
                    jButton1.setEnabled(true);
                    }
                }
                
            }

            

         });
    }
    
    private void Clear_Table1(){
       for (int i = 0; i < jTable1.getRowCount(); i++) {
           Modelo_Tabla.removeRow(i);
           i-=1;
       }
   }
    
    public static DefaultTableModel Modelo_Tabla;

    public void Obtener_Datos() {
        try {
            int i = 0;
            Object row[] = null;

            String consulta;
            consulta = "SELECT count(*) AS Archivos,palabra as Palabra, sum(frecuencia) AS Frecuencia"
                    + " FROM SUPERTABLA JOIN DICCIONARIO ON (SUPERTABLA.id_diccionario=DICCIONARIO.id_diccionario)"
                    + " Where diccionario.nombre ='" + jComboBox1.getSelectedItem().toString().toLowerCase()
                    + "'  GROUP BY Palabra";
            ResultSet rs = baseDatos.obtenerDatos(consulta);
            if (rs != null) {

                while (rs.next()) {
                    Modelo_Tabla.addRow(row);
                    Modelo_Tabla.setValueAt(rs.getString("Palabra"), i, 0);
                    Modelo_Tabla.setValueAt(rs.getInt("Frecuencia"), i, 1);
                    Modelo_Tabla.setValueAt(rs.getInt("Archivos"), i, 2);
                    i++;
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error");
        }
    }

    public void llenarCombo() {
        try {
            DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
            String consulta;
            consulta = "Select * from diccionario";
            
            ResultSet rs = baseDatos.obtenerDatos(consulta);

            modeloCombo.addElement("Seleccione un campo");//es el primer registro q mostrara el combo
            jComboBox1.setModel(modeloCombo);//con esto lo agregamos al objeto al jcombobox
            while (rs.next()) {
                modeloCombo.addElement(rs.getObject("nombre"));
                jComboBox1.setModel(modeloCombo);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString() + " error");
        }
    }

    private void Modelo() {
        try {
            Modelo_Tabla = (new DefaultTableModel(
                    null, new String[]{"Palabra", "Frecuencia", "Archivos"}) {
                        Class[] types = new Class[]{
                            java.lang.String.class,
                            java.lang.Integer.class,
                            java.lang.Integer.class,};
                        boolean[] canEdit = new boolean[]{
                            false, false, false
                        };

                        @Override
                        public Class getColumnClass(int columnIndex) {
                            return types[columnIndex];
                        }

                        @Override
                        public boolean isCellEditable(int rowIndex, int colIndex) {
                            return canEdit[colIndex];
                        }
                    });
            jTable1.setModel(Modelo_Tabla);
            jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            jTable1.getTableHeader().setReorderingAllowed(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + " error");
        }
    }

    public void filtro() {
        trsfiltro.setRowFilter(RowFilter.regexFilter("^" + jTextField1.getText().toLowerCase(), 0));
    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblPalabra;
    // End of variables declaration//GEN-END:variables

}
